### ISSUE TITLE
`/space/create` 생성 시 textarea 글자 수 제한 위치

### ISSUE THREAD

**Issue by hyesungoh** [depromeet/layer#349]
![스크린샷 2024-09-09 오전 1 22 50](https://github.com/user-attachments/assets/e9153b6c-41cb-410a-91c5-2a9005e11f1a)

안녕하세요 ~ 재미있는 서비스 잘 보고 있습니다 👍 

단순 스타일 이슈가 확인되어 이슈 생성 드려요

실행 환경은 파이어폭스 입니당

**Comment by klmhyeonwoo** [comment]
감사합니다 이슈 제보해주셔서 감사합니다!
빠른 수정 후 바로 업데이트 하겠습니다 ☺️
기여해주셔서 감사합니다 🙇🏻‍♂️

**Comment by leeminhee119** [comment]
해당 문제 해결되어 이슈 닫습니다! 제보 감사합니다 🙇‍♀️
